"""empty message

Revision ID: 70014c3e3dc0
Revises: cdee4448da4a
Create Date: 2023-11-14 17:02:58.330340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70014c3e3dc0'
down_revision = 'cdee4448da4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.drop_column('group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
